### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by vitormattos** [LibreCodeCoop/trademark#8]
Is necessary to implement tests and make new release using GitHub Actions.

Each task of this to-do list could be made in separated pull requests.

## to-do
- [ ] Apply linter with php-cs
  Example: https://github.com/LibreSign/libresign/blob/main/.github/workflows/lint-php-cs.yml
- [ ] Implement psalm
  Example: https://github.com/LibreSign/libresign/blob/main/.github/workflows/psalm.yml
- [ ] Use internal PHP linter
  Example: https://github.com/LibreSign/libresign/blob/main/.github/workflows/lint-php.yml
- [ ] Test if all changes was made to publish a new release
- [ ] Pack the new release files and attach to GitHub release.
  https://github.com/svenstaro/upload-release-action
  Example: https://github.com/LibreSign/libresign/blob/main/.github/workflows/appstore-build-publish.yml#L156-L164
